"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { pricingPackages, type Market } from "@/data/pricing";
type View = "home" | "website" | "pricing" | "cms" | "automation" | "qa" | "project";
const actions: { label: string; view?: View; href?: string }[] = [{ label: "Build a Website", view: "website" }, { label: "See Pricing", view: "pricing" }, { label: "CMS / Admin Dashboard", view: "cms" }, { label: "Automation Services", view: "automation" }, { label: "Testing / QA", view: "qa" }, { label: "View Projects", href: "/#projects" }, { label: "Start a Project", view: "project" }];
const choices = [["Landing Page", "landing-page"], ["Business Website", "business-website"], ["E-commerce", "ecommerce"], ["CMS Website", "cms-pro"], ["Custom Web App", "custom-web-application"], ["I'm not sure", "other"]] as const;
export function Assistant() {
 const [open,setOpen]=useState(false), [view,setView]=useState<View>("home"), [market,setMarket]=useState<Market>("india"), [service,setService]=useState("business-website"), [step,setStep]=useState(0), [budget,setBudget]=useState(""), [timeline,setTimeline]=useState(""); const panel=useRef<HTMLDivElement>(null), launcher=useRef<HTMLButtonElement>(null);
 useEffect(()=>{if(!open)return;panel.current?.focus();const escape=(e:KeyboardEvent)=>{if(e.key==="Escape"){setOpen(false);launcher.current?.focus();}};window.addEventListener("keydown",escape);return()=>window.removeEventListener("keydown",escape)},[open]);
 const go=(next:View)=>{setView(next);setStep(0)}, close=()=>{setOpen(false);launcher.current?.focus()};
 return <div className="assistant-root">{open&&<div className="assistant-panel" ref={panel} role="dialog" aria-labelledby="assistant-title" tabIndex={-1}><header><div><strong id="assistant-title">PSDigiLabs Assistant</strong><small>GUIDED CUSTOMER ASSISTANCE</small></div><button onClick={close} aria-label="Minimise assistant">−</button></header><div className="assistant-body" aria-live="polite">{view!=="home"&&<button className="assistant-back" onClick={()=>go("home")}>← Back</button>}
 {view==="home"&&<><Message title="Hi! I'm the PSDigiLabs Assistant." text="What can I help you with?"/><div className="quick-actions">{actions.map(a=>a.href?<Link href={a.href} onClick={close} key={a.label}>{a.label}</Link>:<button onClick={()=>go(a.view!)} key={a.label}>{a.label}</button>)}</div></>}
 {view==="website"&&<><Message title="What are you planning to build?" text="I'll point you to a suitable starting package."/><div className="quick-actions">{choices.map(([label,id])=><Link href={`/contact?service=${id}`} onClick={close} key={id}>{label}<small>{pricingPackages.find(p=>p.id===id)?.price[market]||"We can scope it together"}</small></Link>)}</div></>}
 {view==="pricing"&&<><Message title="Approximate starting prices" text="Final pricing depends on scope, functionality, integrations, content, complexity and delivery requirements."/><div className="assistant-market"><button aria-pressed={market==="india"} onClick={()=>setMarket("india")}>India 🇮🇳</button><button aria-pressed={market==="international"} onClick={()=>setMarket("international")}>International 🌍</button></div><div className="chat-prices">{pricingPackages.slice(0,6).map(p=><p key={p.id}><span>{p.title}</span><strong>{p.price[market]}</strong></p>)}</div><Link className="assistant-cta" href="/contact" onClick={close}>GET AN EXACT QUOTE</Link></>}
 {view==="cms"&&<Info title="CMS & admin dashboards" text="Database-backed websites with content, media and structured-data management through an appropriate admin experience." href="/contact?service=cms-pro" close={close}/>} {view==="automation"&&<Info title="Practical workflow automation" text="API-connected processes, lead routing, email and CRM workflows, form automation and other agreed business processes." href="/contact?service=workflow-automation" close={close}/>} {view==="qa"&&<Info title="Testing & QA support" text="Manual, functional, UI, responsive, regression and exploratory testing with actionable bug reporting." href="/contact?service=manual-testing" close={close}/>} 
 {view==="project"&&<><Message title="Let's narrow down your enquiry." text={step===0?"What service are you interested in?":step===1?"Are you based in India or outside India?":step===2?"What budget range are you considering?":step===3?"When are you hoping to start?":"Great — continue to the enquiry form with your choices prefilled."}/>{step===0&&<select aria-label="Service" value={service} onChange={e=>setService(e.target.value)}>{choices.map(([l,id])=><option value={id} key={id}>{l}</option>)}</select>}{step===1&&<select aria-label="Market" value={market} onChange={e=>setMarket(e.target.value as Market)}><option value="india">India</option><option value="international">Outside India</option></select>}{step===2&&<select aria-label="Budget" value={budget} onChange={e=>setBudget(e.target.value)}><option value="">Not sure yet</option>{(market==="india"?["Below ₹10,000","₹10,000 – ₹25,000","₹25,000 – ₹50,000","₹50,000 – ₹1,00,000","₹1,00,000+"]:["Below $250","$250 – $500","$500 – $1,000","$1,000 – $2,500","$2,500+"]).map(v=><option key={v}>{v}</option>)}</select>}{step===3&&<select aria-label="Timeline" value={timeline} onChange={e=>setTimeline(e.target.value)}><option value="">Just exploring</option>{["As soon as possible","Within 2–4 weeks","Within 1–2 months","2+ months"].map(v=><option key={v}>{v}</option>)}</select>}{step<4?<button className="assistant-cta" onClick={()=>setStep(s=>s+1)}>CONTINUE</button>:<Link className="assistant-cta" href={`/contact?service=${service}&market=${market}${budget?`&budget=${encodeURIComponent(budget)}`:""}${timeline?`&timeline=${encodeURIComponent(timeline)}`:""}`} onClick={close}>CONTINUE TO PROJECT FORM</Link>}</>}
 </div><footer><button onClick={()=>go("home")}>Restart conversation</button><span>Automated assistant</span></footer></div>}<button ref={launcher} className="assistant-launcher" aria-label={open?"Close PSDigiLabs Assistant":"Ask PSDigiLabs"} aria-expanded={open} onClick={()=>setOpen(v=>!v)}><span>{open?"×":"?"}</span><b>{open?"CLOSE":"ASK PSDIGILABS"}</b></button></div>;
}
function Message({title,text}:{title:string;text:string}){return <div className="bot-message"><strong>{title}</strong><p>{text}</p></div>}; function Info({title,text,href,close}:{title:string;text:string;href:string;close:()=>void}){return <><Message title={title} text={text}/><Link className="assistant-cta" href={href} onClick={close}>DISCUSS THIS SERVICE</Link></>}
